### ISSUE TITLE
libxml is missing from tarball

### ISSUE THREAD

**Issue by lovell** [lovell/package-libvips-darwin#4]
It's "keg only" so we need to ensure we link against and copy over the brew-provided version.

See https://github.com/lovell/sharp/issues/1593

**Comment by lovell** [comment]
Waiting will also solve this.
* a future librsvg v3 will remove the dependence on libxml
* a future OS X update will take libxml beyond v2.9.4

**Comment by kleisauke** [comment]
libgsf depends on libxml2 as well. Adding `/usr/local/opt/libxml2/lib/pkgconfig` to the `PKG_CONFIG_PATH` environment variable and rebuilding the dependencies that require libxml2 (i.e. libgsf and librsvg) should ensure that the brew-provided version of libxml2 is included within the tarball.

fwiw, I had a similar problem with a missing `libxml/tree.h` on the `xcode11` base image (see for e.g. [this Travis build](https://travis-ci.org/github/kleisauke/libvips/jobs/677823269#L946)). Adding `/usr/local/opt/libxml2/lib/pkgconfig` to the `PKG_CONFIG_PATH` fixes this[<sup>1</sup>](https://github.com/kleisauke/libvips/blob/5f7502ebf74d31e62c3682426ab2cb14db42d330/.travis.yml#L133)[<sup>2</sup>](https://travis-ci.org/github/kleisauke/libvips/jobs/678050018).

**Comment by lovell** [comment]
Closing as we can now archive this repo.
