### ISSUE TITLE
Update macOS to 10.13 (High Sierra) on Travis

### ISSUE THREAD

**Issue by kleisauke** [lovell/package-libvips-darwin#6]
It seems macOS 10.12 (Sierra) is no longer supported within Homebrew (https://github.com/Homebrew/brew/pull/6500). This causes timeout errors on Travis as it tries to build dependencies from the source:
https://travis-ci.org/lovell/package-libvips-darwin/builds/596560147
(bottles for Sierra are being removed)

Commit https://github.com/kleisauke/homebrew-libvips/commit/0325546b99bb5b154b0c79bc94ba0e240e752c99 fixes this by updating macOS to 10.13 (High Sierra). Travis build:
https://travis-ci.org/kleisauke/homebrew-libvips/builds/596563053

Should I apply that commit to this repo? I tested the tarball on the libvips testsuite in a Travis container with `osx_image: xcode9.2` and did not encounter any problems. Maybe it's also worth testing this on a physical machine.

Note that I used the default macOS image (`osx_image: xcode9.4`), I might be able to lower it to `osx_image: xcode9.3`.

**Comment by lovell** [comment]
Hi Kleis, thanks for researching this and yes please to the fix. The `xcode9.3` image is also based on 10.13 so let's go for that one. https://docs.travis-ci.com/user/reference/osx/#macos-version

**Comment by kleisauke** [comment]
OK, resolved with: https://github.com/lovell/package-libvips-darwin/commit/ddc13acdbc2b7c52a045faaf1f7563622bbfa472.
